In [54]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [55]:
import numpy
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set(style="whitegrid", color_codes=True)

In [56]:
ACTIVITIES = '../data/activities.csv'
CASES = '../data/cases.csv'
CRP = '../data/crp.csv'
DIAG = '../data/diagnose.csv'
DIAGNOSTICS = '../data/diagnostics.csv'
LACT = '../data/lacticacid.csv'
LEUCO = '../data/leucocytes.csv'

In [57]:
activities = pd.read_csv(ACTIVITIES)
cases = pd.read_csv(CASES)
crp = pd.read_csv(CRP)
diagnose = pd.read_csv(DIAG)
diagnostics = pd.read_csv(DIAGNOSTICS)
lacticacide = pd.read_csv(LACT)
leucocytes = pd.read_csv(LEUCO)

In [58]:
activities.T.head()

,0,1,2,3,4,5,6,7,8,9,...,15204,15205,15206,15207,15208,15209,15210,15211,15212,15213
Case-Id,232,425,728,978,11,40,46,51,67,68,...,1047,1048,1048,1048,1049,1049,1049,1049,1049,1049
Case-concept:name,XH,JP,ABA,QKA,K,NaN,TA,YA,OB,PB,...,INA,JNA,JNA,JNA,KNA,KNA,KNA,KNA,KNA,KNA
Event-Id,3078,6195,10599,14200,132,455,521,562,746,760,...,15193,15194,15195,15196,15197,15198,15199,15203,15204,15205
sorting,20,5,6,4,6,14,8,4,14,12,...,3,1,2,3,1,2,3,7,8,9
timestamp,2014-03-27 09:00:00,2014-05-03 18:26:00,2014-10-12 10:10:00,2013-11-16 08:21:00,2014-02-23 21:15:00,2014-11-13 06:00:00,2014-08-10 06:00:00,2014-07-10 10:54:00,2014-12-12 06:00:00,2015-01-19 10:00:00,...,2014-11-03 09:45:51,2014-11-12 16:40:19,2014-11-12 16:47:25,2014-11-12 16:47:39,2014-12-11 22:28:38,2014-12-11 22:52:48,2014-12-11 22:53:16,2014-12-12 04:03:38,2014-12-12 04:03:43,2014-12-12 04:06:38

In [59]:
cases.T.head()

,0,1,2,3,4,5,6,7,8,9,...,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049
id,251,264,887,802,496,455,630,209,276,606,...,908,88,240,217,538,383,612,925,616,453
age,35,90,65,55,80,60,90,70,85,70,...,70,85,90,60,60,75,65,75,90,90

In [60]:
act_case_all = join_df(activities, cases, left_on='Case-Id', right_on='id')

In [80]:
crp.event_id = crp.event_id.astype(int)
crp.head()

   event_id    crp
0       433   74.0
1       438  112.0
2       439  100.0
3         3   21.0
4        10  109.0

In [76]:
crp_act_case = join_df(act_case_all, crp, left_on='Event-Id', right_on='event_id')

In [91]:
crp_act_case.shape

(15214, 11)

In [96]:
crp_act_case.head()
#sum(crp_act_case['crp'].notnull())

,Case-Id,Case-concept:name,Event-Id,sorting,timestamp,Event-Name,org:group,id,age,event_id,crp
0,232,XH,3078,20,2014-03-27 09:00:00,CRP,B,232,90,NaN,NaN
1,425,JP,6195,5,2014-05-03 18:26:00,CRP,B,425,35,NaN,NaN
2,728,ABA,10599,6,2014-10-12 10:10:00,Leucocytes,B,728,75,NaN,NaN
3,978,QKA,14200,4,2013-11-16 08:21:00,Leucocytes,B,978,85,NaN,NaN
4,11,K,132,6,2014-02-23 21:15:00,Leucocytes,B,11,50,NaN,NaN

In [63]:
diagnose.T.head()

,0,1,2,3,4,5,6,7,8,9,...,787,788,789,790,791,792,793,794,795,796
event_id,2170,2557,3173,3507,3954,4202,4308,4767,8197,8742,...,14970,15005,15015,15081,15090,15097,15127,15136,15161,15197
diagnose,A,K,C,AB,EB,D,B,B,E,B,...,B,OE,G,ZB,Z,BA,PE,G,G,QE

In [64]:
diagnose_crp_case = join_df(crp_act_case, diagnose, left_on='Event-Id', right_on='event_id')

In [65]:
diagnostics.T.head()

,0,1,2,3,4,5,6,7,8,9,...,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049
event_id,280,407,423,811,893,898,912,924,941,948,...,15090,15097,15114,15122,15127,15136,15161,15191,15194,15197
diagnosticartastrup,0,0,0,1,0,0,1,0,0,1,...,1,0,0,1,1,0,1,0,0,1
diagnosticblood,1,1,0,1,0,1,1,1,0,1,...,0,0,0,1,1,1,1,0,0,1
diagnosticecg,1,1,0,1,0,1,1,1,0,1,...,1,0,1,1,1,1,1,0,0,1
diagnosticic,1,1,0,1,0,1,1,1,0,1,...,1,0,1,1,1,1,1,0,0,1

In [66]:
diagnostics_diagnose_crp_case = join_df(diagnose_crp_case, diagnostics, left_on='Event-Id', right_on='event_id')

In [67]:
lacticacide.event_id = lacticacide.event_id.astype(int)
lacticacide.T.head()

,0,1,2,3,4,5,6,7,8,9,...,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453
event_id,26.0,165.0,247.0,795.0,884.0,905.0,915.0,1405.0,927.0,955.0,...,15149.0,15154.0,15158.0,15208.0,15166.0,15171.0,15176.0,15179.0,15180.0,15201.0
lacticacid,0.8,1.3,2.1,1.0,1.5,1.0,1.9,1.3,3.0,1.4,...,0.8,0.4,1.2,0.2,7.2,2.8,1.8,2.0,1.4,2.3

In [68]:
lacticacide_diagnostics_diagnose_crp_case = join_df(diagnostics_diagnose_crp_case, lacticacide, left_on='Event-Id', right_on='event_id')

In [69]:
leucocytes.event_id = leucocytes.event_id.astype(int)
leucocytes.T.head()

,0,1,2,3,4,5,6,7,8,9,...,3351,3352,3353,3354,3355,3356,3357,3358,3359,3360
event_id,10599.0,14200.0,132.0,455.0,521.0,562.0,746.0,760.0,793.0,883.0,...,15170.0,15209.0,15173.0,15174.0,15177.0,15181.0,15185.0,15188.0,15200.0,15207.0
leucocytes,2.0,15.9,17.1,17.9,12.4,20.4,7.6,10.8,9.8,8.8,...,1.8,8.9,3.0,5.8,10.7,12.2,18.3,12.0,9.4,8.5

In [70]:
leucocytes_lacticacide_diagnostics_diagnose_crp_case = join_df(lacticacide_diagnostics_diagnose_crp_case, leucocytes, left_on='Event-Id', right_on='event_id')

In [71]:
def join_df(left, right, left_on, right_on=None, suffix='_y'):
    if right_on is None: right_on = left_on
    return left.merge(right, how='left', left_on=left_on, right_on=right_on,
                      suffixes=("", suffix))

In [73]:
leucocytes_lacticacide_diagnostics_diagnose_crp_case.T.head(30)

,0,1,2,3,4,5,6,7,8,9,...,15204,15205,15206,15207,15208,15209,15210,15211,15212,15213
Case-Id,232,425,728,978,11,40,46,51,67,68,...,1047,1048,1048,1048,1049,1049,1049,1049,1049,1049
Case-concept:name,XH,JP,ABA,QKA,K,NaN,TA,YA,OB,PB,...,INA,JNA,JNA,JNA,KNA,KNA,KNA,KNA,KNA,KNA
Event-Id,3078,6195,10599,14200,132,455,521,562,746,760,...,15193,15194,15195,15196,15197,15198,15199,15203,15204,15205
sorting,20,5,6,4,6,14,8,4,14,12,...,3,1,2,3,1,2,3,7,8,9
timestamp,2014-03-27 09:00:00,2014-05-03 18:26:00,2014-10-12 10:10:00,2013-11-16 08:21:00,2014-02-23 21:15:00,2014-11-13 06:00:00,2014-08-10 06:00:00,2014-07-10 10:54:00,2014-12-12 06:00:00,2015-01-19 10:00:00,...,2014-11-03 09:45:51,2014-11-12 16:40:19,2014-11-12 16:47:25,2014-11-12 16:47:39,2014-12-11 22:28:38,2014-12-11 22:52:48,2014-12-11 22:53:16,2014-12-12 04:03:38,2014-12-12 04:03:43,2014-12-12 04:06:38
Event-Name,CRP,CRP,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,...,ER Sepsis Triage,ER Registration,ER Triage,ER Sepsis Triage,ER Registration,ER Triage,ER Sepsis Triage,IV Liquid,IV Antibiotics,Admission NC
org:group,B,B,B,B,B,B,B,B,B,B,...,A,A,C,A,A,C,A,A,A,Q
id,232,425,728,978,11,40,46,51,67,68,...,1047,1048,1048,1048,1049,1049,1049,1049,1049,1049
age,90,35,75,85,50,90,80,90,80,80,...,25,40,40,40,35,35,35,35,35,35
event_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
event_id_y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,15197,NaN,NaN,NaN,NaN,NaN
diagnose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,QE,NaN,NaN,NaN,NaN,NaN
event_id_y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,15194,NaN,NaN,15197,NaN,NaN,NaN,NaN,NaN
diagnosticartastrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticblood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticecg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticlacticacid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticliquor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticother,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticsputum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticurinaryculture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticurinarysediment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticxthorax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
disfuncorg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
hypotensie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
hypoxie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
infectionsuspected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
infusion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN

In [98]:
master = leucocytes_lacticacide_diagnostics_diagnose_crp_case.drop('event_id_y', axis=1)

In [100]:
master.T.head(30)

,0,1,2,3,4,5,6,7,8,9,...,15204,15205,15206,15207,15208,15209,15210,15211,15212,15213
Case-Id,232,425,728,978,11,40,46,51,67,68,...,1047,1048,1048,1048,1049,1049,1049,1049,1049,1049
Case-concept:name,XH,JP,ABA,QKA,K,NaN,TA,YA,OB,PB,...,INA,JNA,JNA,JNA,KNA,KNA,KNA,KNA,KNA,KNA
Event-Id,3078,6195,10599,14200,132,455,521,562,746,760,...,15193,15194,15195,15196,15197,15198,15199,15203,15204,15205
sorting,20,5,6,4,6,14,8,4,14,12,...,3,1,2,3,1,2,3,7,8,9
timestamp,2014-03-27 09:00:00,2014-05-03 18:26:00,2014-10-12 10:10:00,2013-11-16 08:21:00,2014-02-23 21:15:00,2014-11-13 06:00:00,2014-08-10 06:00:00,2014-07-10 10:54:00,2014-12-12 06:00:00,2015-01-19 10:00:00,...,2014-11-03 09:45:51,2014-11-12 16:40:19,2014-11-12 16:47:25,2014-11-12 16:47:39,2014-12-11 22:28:38,2014-12-11 22:52:48,2014-12-11 22:53:16,2014-12-12 04:03:38,2014-12-12 04:03:43,2014-12-12 04:06:38
Event-Name,CRP,CRP,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,...,ER Sepsis Triage,ER Registration,ER Triage,ER Sepsis Triage,ER Registration,ER Triage,ER Sepsis Triage,IV Liquid,IV Antibiotics,Admission NC
org:group,B,B,B,B,B,B,B,B,B,B,...,A,A,C,A,A,C,A,A,A,Q
id,232,425,728,978,11,40,46,51,67,68,...,1047,1048,1048,1048,1049,1049,1049,1049,1049,1049
age,90,35,75,85,50,90,80,90,80,80,...,25,40,40,40,35,35,35,35,35,35
event_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diagnose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,QE,NaN,NaN,NaN,NaN,NaN
diagnosticartastrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticblood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticecg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticlacticacid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticliquor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticother,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticsputum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticurinaryculture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticurinarysediment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticxthorax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
disfuncorg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
hypotensie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
hypoxie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
infectionsuspected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
infusion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
oligurie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
sirscritleucos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [101]:
master1 = master.drop('event_id', axis=1)

In [102]:
master2 = master1.drop('id', axis=1)

In [112]:
master2[master2['Case-Id'] == 232].sort_values(['timestamp'])

,Case-Id,Case-concept:name,Event-Id,sorting,timestamp,Event-Name,org:group,age,crp,diagnose,...,hypoxie,infectionsuspected,infusion,oligurie,sirscritleucos,sirscritheartrate,sirscrittachypnea,sirscrittemperature,lacticacid,leucocytes
9570,232,XH,3059,1,2014-03-17 11:51:43,ER Registration,A,90,NaN,C,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN
9571,232,XH,3060,2,2014-03-17 11:57:15,ER Triage,C,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9572,232,XH,3061,3,2014-03-17 11:57:42,ER Sepsis Triage,A,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5512,232,XH,3062,4,2014-03-17 12:36:00,CRP,B,90,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,232,XH,3063,5,2014-03-17 12:36:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.2
3684,232,XH,3064,6,2014-03-17 12:36:00,LacticAcid,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
9573,232,XH,3065,7,2014-03-17 14:28:58,IV Antibiotics,A,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9574,232,XH,3066,8,2014-03-17 14:28:59,IV Liquid,A,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9575,232,XH,3067,9,2014-03-17 14:30:51,Admission NC,R,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,232,XH,3069,11,2014-03-18 06:00:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.6
5514,232,XH,3068,10,2014-03-18 06:00:00,CRP,B,90,12.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5515,232,XH,3070,12,2014-03-19 06:00:00,CRP,B,90,33.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,232,XH,3071,13,2014-03-19 06:00:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.4
5516,232,XH,3072,14,2014-03-20 06:00:00,CRP,B,90,59.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,232,XH,3073,15,2014-03-20 06:00:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.5
662,232,XH,3075,17,2014-03-21 06:00:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.7
5517,232,XH,3074,16,2014-03-21 06:00:00,CRP,B,90,43.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9577,232,XH,3076,18,2014-03-21 07:24:51,Admission NC,I,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,232,XH,3077,19,2014-03-22 06:00:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.1
0,232,XH,3078,20,2014-03-27 09:00:00,CRP,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,232,XH,3079,21,2014-03-27 09:00:00,Leucocytes,B,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.7
9578,232,XH,3080,22,2014-03-28 08:30:00,Release A,E,90,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
master2[master2['Case-Id'] == 425].sort_values(['sorting'])

,Case-Id,Case-concept:name,Event-Id,sorting,timestamp,Event-Name,org:group,age,crp,diagnose,...,hypoxie,infectionsuspected,infusion,oligurie,sirscritleucos,sirscritheartrate,sirscrittachypnea,sirscrittemperature,lacticacid,leucocytes
10945,425,JP,6191,1,2014-05-03 18:14:32,ER Registration,A,35,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
10946,425,JP,6192,2,2014-05-03 18:22:17,ER Triage,C,35,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10947,425,JP,6193,3,2014-05-03 18:22:34,ER Sepsis Triage,A,35,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1396,425,JP,6194,4,2014-05-03 18:26:00,Leucocytes,B,35,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
1,425,JP,6195,5,2014-05-03 18:26:00,CRP,B,35,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
master2['Event-Name'].unique()

array(['CRP', 'Leucocytes', 'LacticAcid', 'Admission NC', 'IV Liquid',
       'ER Triage', 'Release B', 'IV Antibiotics', 'ER Sepsis Triage',
       'ER Registration', 'Return ER', 'Release A', 'Release D',
       'Admission IC', 'Release C', 'Release E'], dtype=object)

In [108]:
master2.T.head(50)

,0,1,2,3,4,5,6,7,8,9,...,15204,15205,15206,15207,15208,15209,15210,15211,15212,15213
Case-Id,232,425,728,978,11,40,46,51,67,68,...,1047,1048,1048,1048,1049,1049,1049,1049,1049,1049
Case-concept:name,XH,JP,ABA,QKA,K,NaN,TA,YA,OB,PB,...,INA,JNA,JNA,JNA,KNA,KNA,KNA,KNA,KNA,KNA
Event-Id,3078,6195,10599,14200,132,455,521,562,746,760,...,15193,15194,15195,15196,15197,15198,15199,15203,15204,15205
sorting,20,5,6,4,6,14,8,4,14,12,...,3,1,2,3,1,2,3,7,8,9
timestamp,2014-03-27 09:00:00,2014-05-03 18:26:00,2014-10-12 10:10:00,2013-11-16 08:21:00,2014-02-23 21:15:00,2014-11-13 06:00:00,2014-08-10 06:00:00,2014-07-10 10:54:00,2014-12-12 06:00:00,2015-01-19 10:00:00,...,2014-11-03 09:45:51,2014-11-12 16:40:19,2014-11-12 16:47:25,2014-11-12 16:47:39,2014-12-11 22:28:38,2014-12-11 22:52:48,2014-12-11 22:53:16,2014-12-12 04:03:38,2014-12-12 04:03:43,2014-12-12 04:06:38
Event-Name,CRP,CRP,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,Leucocytes,...,ER Sepsis Triage,ER Registration,ER Triage,ER Sepsis Triage,ER Registration,ER Triage,ER Sepsis Triage,IV Liquid,IV Antibiotics,Admission NC
org:group,B,B,B,B,B,B,B,B,B,B,...,A,A,C,A,A,C,A,A,A,Q
age,90,35,75,85,50,90,80,90,80,80,...,25,40,40,40,35,35,35,35,35,35
crp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diagnose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,QE,NaN,NaN,NaN,NaN,NaN
diagnosticartastrup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticblood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticecg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticlacticacid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticliquor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticother,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticsputum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticurinaryculture,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
diagnosticurinarysediment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
diagnosticxthorax,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
disfuncorg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
hypotensie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
hypoxie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
infectionsuspected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
infusion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
oligurie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
sirscritleucos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
sirscritheartrate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
sirscrittachypnea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
sirscrittemperature,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
lacticacid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
leucocytes,NaN,NaN,2,15.9,17.1,17.9,12.4,20.4,7.6,10.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
SAVE_PATH = '../data/master.csv'
master2.to_csv(SAVE_PATH, index=False)

In [106]:
len(master2.columns)

33